spring:
  datasource:
    url: jdbc:postgresql://sofia-itusaca-postgresempleado-3akzwd:5432/db_taller
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 3408